name = "leanstack-bff"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "leanstack-bff-prod"

[env.staging]
name = "leanstack-bff-staging"

[[env.production.vars]]
SUPABASE_URL = "your-production-supabase-url"
SUPABASE_ANON_KEY = "your-production-supabase-anon-key"

[[env.staging.vars]]
SUPABASE_URL = "your-staging-supabase-url"
SUPABASE_ANON_KEY = "your-staging-supabase-anon-key"
